# Site settings
title: Freifunk Waldheim
email: kontakt@freifunk-mittelsachsen.de
description: > # this means to ignore newlines until "baseurl:"
    Freifunk Waldheim - kostenloses und selbstorganisiertes Netzwerk in
    Waldheim und Umgebung
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.freifunk-waldheim.de" # the base hostname & protocol for your site
twitter_username: freifunkmtl
github_username:  Freifunk-Mittelsachsen
exclude: [Rakefile,  docs/*, templates/*]

# Build settings
markdown: kramdown

post:
  template: templates/_post.txt
  extension: md
page:
  template: templates/_page.txt
  extension: md

editor: atom

git:
  branch: master
