# Site settings
title: Freifunk Mittelsachsen.
subtitle: Das freie und kostenlose Bürger-Datennetz in Mittelsachsen
email: kontakt@freifunk-mittelsachsen.de
description: > # this means to ignore newlines until "baseurl:"
    Freifunk Mittelsachsen - kostenloses und selbstorganisiertes Netzwerk in
    den Städten und Gemeinden Mittelsachsens
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://www.freifunk-mittelsachsen.de" # the base hostname & protocol for your site
twitter_username: freifunkmtl
github_username:  Freifunk-Mittelsachsen
exclude: [Rakefile,  docs/*, templates/*]

paginate: 7
paginate_path: "/news/page:num/"

# Build settings
markdown: kramdown

gems: [jekyll-paginate]

post:
  template: templates/_post.txt
  extension: md
page:
  template: templates/_page.txt
  extension: md

editor: atom

git:
  branch: master
